### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.ao'

### ISSUE THREAD

**Issue by julianorinaldi** [sangyun884/HR-VITON#37]
Error with ModuleNotFoundError: No module named 'torch.ao'

python3 test_generator.py --occlusion --test_name test --gpu_ids 0 --checkpoint_dir checkpoint --dataroot data/zalando-hd-resized --data_list test_pairs.txt --tocg_checkpoint checkpoint/mtviton.pth --gen_checkpoint checkpoint/gen.pth --output_dir out
/home/jrinaldi/miniconda3/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/jrinaldi/miniconda3/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZNK3c106IValue23reportToTensorTypeErrorEv
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "test_generator.py", line 4, in <module>
    from torchvision.utils import make_grid as make_image_grid
  File "/home/jrinaldi/miniconda3/lib/python3.8/site-packages/torchvision/__init__.py", line 7, in <module>
    from torchvision import models
  File "/home/jrinaldi/miniconda3/lib/python3.8/site-packages/torchvision/models/__init__.py", line 18, in <module>
    from . import quantization
  File "/home/jrinaldi/miniconda3/lib/python3.8/site-packages/torchvision/models/quantization/__init__.py", line 3, in <module>
    from .mobilenet import *
  File "/home/jrinaldi/miniconda3/lib/python3.8/site-packages/torchvision/models/quantization/mobilenet.py", line 1, in <module>
    from .mobilenetv2 import *  # noqa: F401, F403
  File "/home/jrinaldi/miniconda3/lib/python3.8/site-packages/torchvision/models/quantization/mobilenetv2.py", line 6, in <module>
    from torch.ao.quantization import QuantStub, DeQuantStub
ModuleNotFoundError: No module named 'torch.ao'

**Comment by charlotte1esquirol** [comment]
Hello,
How did you solve your issue please ? I have the same.
Thank you
Sabrina

**Comment by julianorinaldi** [comment]
Hello, I can with these libs

pip3 install -q --no-cache-dir --upgrade pip
pip3 install -q --no-cache-dir torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.1 torchtext==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
pip3 install -q --no-cache-dir opencv-python torchgeometry Pillow tqdm tensorboardX scikit-image scipy

**Comment by WhaSukGO** [comment]
```py
# Change this line
from torch.ao.quantization import DeQuantStub, QuantStub
# to
from torch.quantization import DeQuantStub, QuantStub
```
