### ISSUE TITLE
[train_condition.py] Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by thuongmhh** [sangyun884/HR-VITON#47]
Trying to train try-on condition generator using the script and got the error.
python3 train_condition.py --cuda {True} --gpu_ids {gpu_ids} --Ddownx2 --Ddropout --lasttvonly --interflowloss --occlusion

`Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\TryOn\hr_viton\train_condition.py", line 498, in <module>
    main()
  File "C:\Users\Admin\Desktop\TryOn\hr_viton\train_condition.py", line 489, in main
    train(opt, train_loader, val_loader, test_loader, board, tocg, D)
  File "C:\Users\Admin\Desktop\TryOn\hr_viton\train_condition.py", line 266, in train
    loss_G_GAN = criterionGAN(pred_segmap, True)
  File "C:\Users\Admin\Desktop\TryOn\hr_viton\networks.py", line 295, in __call__
    loss += self.loss(pred, target_tensor)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl   
    return forward_call(*input, **kwargs)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\nn\modules\loss.py", line 520, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\nn\functional.py", line 3112, in mse_loss
    return torch._C._nn.mse_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

How can I fix it?

**Comment by charlotte1esquirol** [comment]
Hi I have a issue when I try to test the model and I think it's also a gpu/cpu issue so did you resolve yours? 

<img width="979" alt="Capture d’écran 2023-01-15 à 13 55 36" src="https://user-images.githubusercontent.com/94962700/212541971-eaeba43d-a365-47e6-b945-c8b8be9507e7.png">

there is a screenshot of mine. Maybe you can help me!
Kind regards,
Sabrina

**Comment by tuyendb** [comment]
> Hi I have a issue when I try to test the model and I think it's also a gpu/cpu issue so did you resolve yours?
> 
> <img alt="Capture d’écran 2023-01-15 à 13 55 36" width="979" src="https://user-images.githubusercontent.com/94962700/212541971-eaeba43d-a365-47e6-b945-c8b8be9507e7.png">
> 
> there is a screenshot of mine. Maybe you can help me! Kind regards, Sabrina

you should check the model device, your inputs used cuda but your model didnt

**Comment by OliverVarnce** [comment]
Who can tell me, how to prepare train_pairs.txt and test.pairs?
