### ISSUE TITLE
train_generator.py

### ISSUE THREAD

**Issue by OliverVarnce** [sangyun884/HR-VITON#55]
I have trained my model in train_condition.py. As results, I have tocg_final.pth and D_final.pth.

But.... I'm trying to execute train_generator.py as
`python3 train_generator.py --cuda True --name test -b 4 -j 8 --gpu_ids 0 --tocg_checkpoint checkpoints/test/tocg_final.pth --occlusion`

But have an error in first step:
`Traceback (most recent call last):
  File "train_generator.py", line 706, in <module>
    main()
  File "train_generator.py", line 696, in main
    train(opt, train_loader, test_loader, test_vis_loader, board, tocg, generator, discriminator, model)
  File "train_generator.py", line 198, in train
    inputs = train_loader.next_batch()
  File "/home/user/content/HR-VITON/cp_dataset.py", line 422, in next_batch
    batch = self.data_iter.__next__()
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/user/.local/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/content/HR-VITON/cp_dataset.py", line 199, in __getitem__
    im_c = im * pcm + (1 - pcm)
RuntimeError: The size of tensor a (256) must match the size of tensor b (296) at non-singleton dimension 1`

What's wrong?

**Comment by Yomiko11** [comment]
> 我在 train_condition.py 中训练了我的模型。结果，我有 tocg_final.pth 和 D_final.pth。
> 
> 但。。。。 我正在尝试执行train_generator.py `python3 train_generator.py --cuda True --name test -b 4 -j 8 --gpu_ids 0 --tocg_checkpoint checkpoints/test/tocg_final.pth --occlusion`
> 
> 但是第一步有错误：
> 
> > 回溯（最近调用最后一次）：文件“train_generator.py”，第 706 行，在 main（） 文件中  文件“train_generator.py”，第 696 行，在 main train（opt， train_loader， test_loader， test_vis_loader， board， tocg， generator， discriminator， model） 文件“train_generator.py”，第 297 行，在第 fake_concat = torch.cat（（parse， output_paired）， dim=1） RuntimeError：张量的大小必须匹配，维度 1 除外。预期大小为 192，但列表中张量编号 1 的大小为 128。
> 
> 我正在使用 192x296 大小的图像和准备好的数据集，我在代码中有 --fine_width 192 --fine_height 296 作为默认值。
> 
> 怎么了？
> 
> UPD：我认为问题在于 output_paired = generator（torch.cat（（agnostic， pose， warped_cloth_paired）， 1）， parse） 输出中张量的大小不是 192，而是 128。它是如何工作的，我仍然不明白......

Have you solved it? I have the same situation as you
